= GraphXR 3.3.0 Release Notes

*Release Date:* October 14, 2025

GraphXR 3.3.0 introduces support for the GraphXR Database Proxy and adds a new API for Sphere layout. The user interface includes refinements to the left menu and legend, and query panel enhancements for Spanner Graph users. Multi-factor authentication is strengthened. Issues with Sandbox functionality and limits to project creation have been resolved.

NOTE: In a GraphXR project, click the Kineviz logo at the bottom left, choose *_About_*, then click on the current release tag for a digest of features introduced in current and past releases.

== New Features 3.3.0

* *Usability Enhancements*
** Improved visibility for selected items in the left menu by reducing blurriness, adding a highlight circle, and introducing shadow effects.(GXR-3050)  
** Added a paintbrush icon in the legend to open the style setting dialog (for Categories only - for other items in legend lists you still click a dot or line to open the dialog).(GXR-3174). 
** Refined design of the Cypher/GQL toggle for Spanner Graph query (GXR-3160).
 
* *Performance Enhancements* 
 
* *Improved Security and User Access*  
** Additional Multi-Factor Authentication(MFA), using either the site domain or configured app name as issuer. (GXR-3124)

* *Configuration Enhancements* 
** Google Cloud Integration
*** Added support for the GraphXR Database Proxy, enabling external database connectivity and improved data flow. (GXR-3176) 

* *GraphXR API* 
** Sphere Layout added for advanced visualization control(GXR-3167).  
 

== Bug Fixes 
* Fixed an issue preventing the sandbox from functioning correctly in advanced settings(GXR-3175).  
* Resolved a bug restricting users to a maximum of three projects even when the plan period was active (GXR-3151).  
  
== Removed 3.3.0

* None

== Extensions 3.3.0
* *Graph Composer*
* *Grove* Observable-based javascript notebooks

NOTE: For information about additional extensions, please contact https://www.kineviz.com[Kineviz].
 
== Supported Environments 3.3.0

* WINDOWS, MAC OSX, AND LINUX
* CLOUD, PRIVATE CLOUD, AND ON-PREMISES DATA HOSTING 
* The GraphXR client runs best in Google Chrome; works in Safari. Compatibility with other browsers may vary.
+
_For more information,_ please contact https://www.kineviz.com[Kineviz].