= Kineviz Extensions

Kineviz has developed extensions that enhance or customize Kineviz for the needs of specific user communities.

Kineviz includes the following extensions by default:

* xref:./grove.adoc[*_Grove_*] for building reproducible workflows, dashboards, and learning resources in an observable-based javascript notebook environment.
* xref:./file-manager.adoc[*_Files_*] for visibility into *Agent* system prompt and skills files, *Grove* notebooks, and internal KoreDB database files.
* xref:./text-editor.adoc[*_Text Editor_*] to edit markdown and other files managed within a *Kineviz* project. For convenience, the *_Text Editor_* can be opened directly within the *_Files_* manager panel.  

For Enterprise subscriptions, additional extensions are available, including:

* *SeekerXR*, a one-stop platform for rapid, cost-effective crime and risk investigation. It is designed by investigators and for investigators, in partnership with Harod Associates. 
* Extended connection to specific SQL, document, or mixed format databases.

NOTE: For more information, please contact https://www.kineviz.com[Kineviz].



