= Import Data

If you have access to an exported *Kineviz* project, you can xref:./import-a-project.adoc[*import the entire project*]. The *_Import Project_* button on the *_Projects_* home page adds and opens any exported _.graphxrproject_ file to your *Kineviz* account. The imported project will include its UI configuration, styling template, managed files, views, and internal datastore. 

More often, though, you will be importing data into a new project you just created. When you enter a project for the first time, it will be empty. You can import data to the project canvas from many different sources, including:

* xref:./import-by-drag-and-drop.adoc[Import by drag and drop]. Files you can drag and drop include CSV or Excel files, JSON files, and data views exported as a CSV or Excel archive, a _.graphxr_ file, or a _.graphxrsnapshots_ archive.

* xref:./query-graphdb.adoc[Query a Graph Database]. You can perform no-code query in the  project *_Query / Search_* bar, use the *_Expand_* tool to expand the graph through its relationships, pull by category or relationship, or enter and run a Cypher or GQL query.  

* Query a xref:./import-via-mapping.adoc[*_CSV_*] file.
** Query a connected xref:./query-sql.adoc[*_SQL_*] database and import the resulting table as graph data.
+
For a CSV file or a SQL table, the Kineviz xref:./import-via-mapping.adoc[*_Mapping Editor_*] lets you transform the data in a single table according to a graph model you specify. 
+
* Query a JSON file or perform a Gremlin query on a connected database.

* xref:./load-a-saved-view.adoc[Load a project's data *_View_*] and access xref:g-user:data-share-views.adoc[Shared views]. 

* For Enterprise users, advanced *Kineviz* extensions are available to import data from a variety of graph or composite databases, and to craft reproducible workflows for importing data.

